.Dd March 31, 2005
.Os
.Dt SVNEOL 1 LOCAL
.\"
.\"
.\"
.\"
.\"
.Sh NAME
.Nm svneol
.Nd clean up line endings
.\"
.\"
.\"
.\"
.\"
.Sh SYNOPSIS
.Nm
.\"
.\"
.\"
.\"
.\"
.Sh DESCRIPTION
When a file in a Subversion working copy has the 'svn:eol-style' property set,
.Xr svn 1
checks the line endings in that file for consistency. If the newlines are
inconsistent -- i.e., they are a mixture of Windows ('\er\en'), legacy Macintosh
('\er'), and/or Unix ('\en') newlines -- then an error is raised and the propset
fails. The file can still be forced into the repository, but then you have
broken data in your repo.
.Nm
is a
.Xr python 1
script that traverses the tree rooted at
.Pa ./
and cleans up the line endings in all text files.
The definition of a text file is taken from the current user's
.Xr svn 1
config file, which is assumed to be at:
.Bd -literal -offset indent
.Pa ~/.subversion/config
.Ed
.Pp
Specifically, text files are those with filenames matching any key in the
[auto-props] section with the value,
.Sq svn:eol-style=native .
These files are opened, and all instances of
(Windows newline) are replaced with
.Sq \en
(Unix newline).

The tree does not have to be an
.Xr svn 1
working copy in order to be processed successfully.
.\"
.\"
.\"
.\"
.\"
.Sh IMPLEMENTATION NOTES
This program was written with FreeBSD 4.11, Python 2.4, and Subversion 1.1.0.
.\"
.\"
.\"
.\"
.\"
.Sh EXAMPLES
.\"
.\"
.\"
.\"
.\"
.Sh SEE ALSO
.Xr svn 1
.\"
.\"
.\"
.\"
.\"
.Sh AUTHORS
.Bl -item -compact
.It
(c) 2005 Chad Whitacre <http://www.zetaweb.com/>
.It
This program is beerware. If you like it, buy me a beer someday.
.It
No warranty is expressed or implied.
.El
