.Dd March 30, 2005
.Os
.Dt ZOPEME 1 LOCAL
.\"
.\"
.\"
.\"
.\"
.Sh NAME
.Nm svneol
.Nd create a ZEO-configured Zope instance
.\"
.\"
.\"
.\"
.\"
.Sh SYNOPSIS
.Nm
.Op Ar --force
.Ar name
.Op Ar port
.\"
.\"
.\"
.\"
.\"
.Sh DESCRIPTION
.Nm
creates a Zope instance that is configured with ZEO. It assumes that the
following paths exist:
.Bl -item -offset indent
.It
.Pa /usr/local/zope/rc.d/
.It
.Pa /usr/local/zope/zope/bin/mkzeoinstance.py
.It
.Pa /usr/local/zope/zope/bin/mkzopeinstance.py
.El
.Pp
It creates the ZEO client and server instances at:
.Bl -item -offset indent
.It
.Pa ./ Ns << Ns Ar name Ns >> Ns Pa /client-1
.It
.Pa ./ Ns << Ns Ar name Ns >> Ns Pa /server
.El
.Pp
If
.Pa ./ Ns << Ns Ar name Ns >>
already exists, it is not overwritten, unless the
.Ar --force
argument is given. After the client and server are created, they are customized
as follows
.Ns ( Ns Ar port
defaults to 8080):
.Bl -bullet -offset indent
.It
sets the HTTP port to
.Ar port
.It
sets the FTP port to
.Ar port
+ 1
.It
sets the ZEO port to
.Ar port
+ 9
.It
sets the effective-user to the user that
.Nm
is run as
.El
.Pp
Lastly,
.Nm
creates a script at:
.Bl -item -offset indent
.It
.Pa /usr/local/zope/rc.d/ Ns << Ns Ar name Ns >> Ns Pa .sh
.El
.Pp

This script can be used to start, stop, and restart the Zope+ZEO instance.

.\"
.\"
.\"
.\"
.\"
.Sh IMPLEMENTATION NOTES
This program was written with FreeBSD 4.11, Python 2.4, and Zope 2.7.4.
.\"
.\"
.\"
.\"
.\"
.Sh EXAMPLES
.Bd -literal
% PATH=/usr/local/zope/rc.d
% cd /usr/local/zope/instances
% svneol foo
.Ns ...
% svneol bar_8000 8000
.Ns ...
% ls
bar_8000        foo
% bar_8000.sh start
.Ns . daemon process started, pid=12345
started bar_8000 zeo server
.Ns . daemon process started, pid=12346
started bar_8000 zeo client
%
.Ed
.\"
.\"
.\"
.\"
.\"
.Sh SEE ALSO
.Xr rc 8
.\"
.\"
.\"
.\"
.\"
.Sh AUTHORS
.Bl -item -compact
.It
(c) 2005 Chad Whitacre <http://www.zetaweb.com/>
.It
This program is beerware. If you like it, buy me a beer someday.
.It
No warranty is expressed or implied.
.El
