.Dd May 30, 2005
.Os
.Dt LICENSOR 1 LOCAL
.\"
.\"
.\"
.\"
.\"
.Sh NAME
.Nm licensor
.Nd adds license boilerplate to a tree of files
.\"
.\"
.\"
.\"
.\"
.Sh SYNOPSIS
.Nm
.Ar license-path
.\"
.\"
.\"
.\"
.\"
.Sh DESCRIPTION
.Nm
is a
.Xr python 1
program that adds license and copyright boilerplate to a tree of files.
.Nm
walks the tree rooted in the current working directory, and adds the boilerplate
found in the file at
.Ar license-path
to each file.

The power and convenience of
.Nm
are in the formatting plugins that are available for various filetypes. This
means that
.Nm
adds its boilerplate using comment characters germane to a given filetype, and
in a location in the file suitable to the filetype. Here are the current plugins:
.Bl -hang -offset indent
.\"
.\"
.It Nm extension
comment char; location notes
.\"
.\"
.It Nm sh
#; following an initial hashbang
.\"
.\"
.It Nm py (projected)
#; following an initial hashbang, or an initial ## comment block (for Zope scripts)
.\"
.\"
.It Nm man pages (ext is 1..9) (projected)
\&.\\"; at the top of the file
.\"
.El
.Pp
.\"
.\"
.\"
.\"
.\"
.Sh IMPLEMENTATION NOTES
This program is known to work with the following software:
.Pp
.Bl -dash -offset indent -compact
.It
FreeBSD 4.11
.It
Python 2.3.5, 2.4
.El
.\"
.\"
.\"
.\"
.\"
.\".Sh FILES
.\"
.\"
.\"
.\"
.\"
.Sh EXAMPLES
.Bd -literal
$ cd ~/FooProject/
$ licensor license.txt
$
.Ed
.\"
.\"
.\"
.\"
.\"
.Sh SEE ALSO
.Xr python 1
.\"
.\"
.\"
.\"
.\"
.\".Sh HISTORY
.\".Bl -hang
.\".It Em 2005-04-01
.\"released version 0.8
.\".El
.\"
.\"
.\"
.\"
.\"
.Sh AUTHORS
.Bl -item -compact
.It
(c) 2005 Chad Whitacre <http://www.zetaweb.com/>
.It
This program is beerware. If you like it, buy me a beer someday.
.It
No warranty is expressed or implied.
.El
.\"
.\"
.\"
.\"
.\"
.\".Sh TODO
