.Dd June 15, 2006
.Os
.Dt SANITY.CONF 5 LOCAL
.\"
.\"
.\"
.\"
.\"
.Sh NAME
.Nm sanity.conf
.Nd configuration file for
.Xr sanity 1
.\"
.\"
.\"
.\"
.\"
.Sh DESCRIPTION
.Xr sanity 1
requires that four variables be set in a configuration file at
.Pa /usr/local/etc/sanity.conf Ns :

.Bl -tag -offset indent
.It email_addy
an email address to which emergency notifications should be sent
.It porter_path
the path to a porter installation (there is no porter man page yet)
.It server_ip
the IP address of the server to check for
.Xr ping 8
.It timeout
the number of seconds to wait for a response before declaring a website in error
.El

See
.Xr sanity 1
for details of how these variables are used. See the
.Xr python 1
documentation for the ConfigParser module documentation for the general format
of this file.
.Xr sanity 1
parses
.Nm
using the RawConfigParser class.
.\"
.\"
.\"
.\"
.\"
.Sh EXAMPLES
Here is an example
.Nm
file:
.Bd -literal
[default]
email_addy  = emergency@example.com
porter_path = /usr/local/porter
server_ip   = 10.0.0.107
timeout     = 5
.Ed
.\"
.\"
.\"
.\"
.\"
.Sh SEE ALSO
.Xr sanity 1
.\"
.\"
.\"
.\"
.\"
.Sh AUTHORS
.Bl -item -compact
.It
(c) 2005-2006 Chad Whitacre <http://www.zetaweb.com/>
.It
This program is beerware. If you like it, buy me a beer someday.
.It
No warranty is expressed or implied.
.El