.Dd March 30, 2005
.Os
.Dt ZOPEME 1 LOCAL
.\"
.\"
.\"
.\"
.\"
.Sh NAME
.Nm zopeme
.Nd create a ZEO-configured Zope instance
.\"
.\"
.\"
.\"
.\"
.Sh SYNOPSIS
.Nm
.Ar path
.Ar port-number
.\"
.\"
.\"
.\"
.\"
.Sh DESCRIPTION
.Nm
creates a Zope instance that is configured with ZEO. It assumes that the
following directories exist:
.Bl -item -offset indent
.It
.Pa /usr/local/zope/rc.d/
.It
.Pa /usr/local/zope/zope/bin/
.El
.Pp
It creates the ZEO client and server instances at:
.Bl -item -offset indent
.It
.Pa ./ Ns << Ns Ar path Ns >>_<< Ns Ar port-number Ns >>/client-1
.It
.Pa ./ Ns << Ns Ar path Ns >>_<< Ns Ar port-number Ns >>/server
.El
.Pp
Then it customizes the ZEO client and server installations as follows:
.Bl -bullet -offset indent
.It
sets the HTTP port to
.Ar port
.It
sets the FTP port to
.Ar port
+ 1
.It
sets the ZEO port to
.Ar port
+ 9
.It
sets the effective-user to the user that
.Nm
is run as
.El
.Pp
Lastly,
.Nm
creates a script at:
.Bl -item -offset indent
.It
.Pa /usr/local/zope/rc.d/ Ns << Ns Ar path Ns >>_<< Ns Ar port-number Ns >>.sh
.El
.Pp
This script can be used to start, stop, and restart the Zope+ZEO instance.
.\"
.\"
.\"
.\"
.\"
.Sh IMPLEMENTATION NOTES
This program was written with FreeBSD 4.11, Python 2.4, and Zope 2.7.4.
.\"
.\"
.\"
.\"
.\"
.Sh EXAMPLES
.Bl -item
.It
% zopeme foobar 8080
.El
.\"
.\"
.\"
.\"
.\"
.Sh SEE ALSO
.Xr rc 8
.\"
.\"
.\"
.\"
.\"
.Sh AUTHORS
.Bl -item -compact
.It
(c) 2005 Chad Whitacre <http://www.zetaweb.com/>
.It
This program is beerware. If you like it, buy me a beer someday.
.It
No warranty is expressed or implied.
.El
