#include <stdio.h>

main()
{
    int c;

    while ((c = getchar()) != EOF) {
        putchar(c);
        if (c == ' ') {
            while((c = getchar()) == ' ')
                ;
            putchar(c);
        }
    }
}


/* Mistakes:

#include <stdio.h>
main()
{
    int c;
    c = 'A';
    printf("%s", c);
}

This results in a segmentation fault:

whit537@josemaria$ gdb a.out a.out.core
GNU gdb 6.1.1 [FreeBSD]
Copyright 2004 Free Software Foundation, Inc.
GDB is free software, covered by the GNU General Public License, and you are
welcome to change it and/or distribute copies of it under certain conditions.
Type "show copying" to see the conditions.
There is absolutely no warranty for GDB.  Type "show warranty" for details.
This GDB was configured as "i386-marcel-freebsd"...(no debugging symbols found)...
Core was generated by `a.out'.
Program terminated with signal 11, Segmentation fault.
Reading symbols from /lib/libc.so.6...(no debugging symbols found)...done.
Loaded symbols for /lib/libc.so.6
Reading symbols from /libexec/ld-elf.so.1...(no debugging symbols found)...done.
Loaded symbols for /libexec/ld-elf.so.1
#0  0x2811fac7 in __vfprintf () from /lib/libc.so.6
(gdb) where
#0  0x2811fac7 in __vfprintf () from /lib/libc.so.6
#1  0x28120684 in vfprintf () from /lib/libc.so.6
#2  0x2810df73 in printf () from /lib/libc.so.6
#3  0x0804863a in main ()
(gdb) q
whit537@josemaria$
