.Dd March 30, 2005
.Os
.Dt ZOSH 1 LOCAL
.\"
.\"
.\"
.\"
.\"
.Sh NAME
.Nm zosh
.Nd provides a shell-like interface on a ZODB
.\"
.\"
.\"
.\"
.\"
.Sh SYNOPSIS
.Nm
.Op zosh
.Ar name
.Op Ar INSTANCE_HOME
.\"
.\"
.\"
.\"
.\"
.Sh DESCRIPTION
.Nm
simulates a Unix-like shell inside a ZODB.
.\"
.\"
.\"
.\"
.\"
.Sh IMPLEMENTATION NOTES
This program was written with FreeBSD 4.11, Python 2.4.1, and Zope 2.7.5.
.\"
.\"
.\"
.\"
.\"
.Sh EXAMPLES
.Bd -literal
% cd /usr/local/zope/instances/foo-instance
% zosh foo
.Ns ...
%
.Ed
.\"
.\"
.\"
.\"
.\"
.Sh SEE ALSO
.\"
.\"
.\"
.\"
.\"
.Sh AUTHORS
.Bl -item -compact
.It
(c) 2005 Chad Whitacre <http://www.zetaweb.com/>
.It
This program is beerware. If you like it, buy me a beer someday.
.It
No warranty is expressed or implied.
.El
